### ISSUE TITLE
Fedora PoC feedback

### ISSUE THREAD

**Issue by TomasTomecek** [openscanhub/openscanhub#211]
First of all, I'm so happy to see this project finally being open source and proposed in Fedora \o/

One thing I am missing in the PoC is a tutorial how to use it:
- I couldn't find openscanhub in the official Fedora repos
- No mention of how to set it up locally via CLI
- Took me a bit of time even to log in
- I found the page in the end to submit a scan via webui but since it's connected to stg.koji it wasn't too useful

I suggest providing a simple-to-use guide how I can run a scan of a locally created SRPM.

**Comment by siteshwar** [comment]
> First of all, I'm so happy to see this project finally being open source and proposed in Fedora \o/
> 
> One thing I am missing in the PoC is a tutorial how to use it:
> 
> * I couldn't find openscanhub in the official Fedora repos

This is just a prototype deployment and we do not have an official production deployment yet. So we have not released the client in the Fedora repositories yet. There is an [issue](https://github.com/openscanhub/openscanhub/issues/195) related to this.

> * No mention of how to set it up locally via CLI

I believe accessing it through web ui is much simpler for new users.

> * Took me a bit of time even to log in

It is possibly because Fedora staging authentication server is slow.

> * I found the page in the end to submit a scan via webui but since it's connected to stg.koji it wasn't too useful
> 
> I suggest providing a simple-to-use guide how I can run a scan of a locally created SRPM.

It would be good to have. But I still believe accessing it through web ui is still much simpler.

**Comment by ferdnyc** [comment]
> > * No mention of how to set it up locally via CLI
> 
> I believe accessing it through web ui is much simpler for new users.

And that will **always** be true by definition, if it's the only method documented. (Technically local setup is documented at [../../docs/development.md](../../docs/development.md), but even that only provides a local version of the web service.)

> > I suggest providing a simple-to-use guide how I can run a scan of a locally created SRPM.
> 
> It would be good to have. But I still believe accessing it through web ui is still much simpler.

Simpler for whom? 

Simpler for the developers, to only have to implement one interface, sure.

Simpler for the users, OTOH — that isn't really for you to say. Not if it's based on nothing more than your personal perspective.

(Especially since the current web interface has some rather severe accessibility issues, which I'll document in a new issue momentarily. For users who rely on assistive technologies or have reduced visual acuity, the current web interface is not only **not-** simple, it may be almost unusable. Whereas getting the same output dumped into a terminal session would make it accessible to all users.)

Now, keep in mind, a local scanning tool / commandline interface doesn't have to be a CLI implementation of **the _entire_ openscanhub system**. Presumably there are underlying command-line tools (or perhaps Python scripts) which openscanhub uses behind-the-scenes to perform the actual scanning functions. Providing users with the necessary info to manually run just those scans in the same manner as openscanhub would, so they can get the results _without_ the web-based formatting and presentation, could be a reasonable first step.

**Comment by kdudka** [comment]
@ferdnyc Thanks for feedback!  The development environment is useful mainly for developers of OpenScanHub.  It is of course not needed for users of OpenScanHub.  Apart from the web UI, users can either use the OpenScanHub client to trigger scans on the remote service, or even run the scans with `csmock` locally if they have enough resources for that.  There is no doubt that documentation for both the approaches needs to be improved though.

**Comment by siteshwar** [comment]
> First of all, I'm so happy to see this project finally being open source and proposed in Fedora \o/
> 
> One thing I am missing in the PoC is a tutorial how to use it:
> 
> * I couldn't find openscanhub in the official Fedora repos

It is currently tracked through a [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=2275304). Alternatively, users can download it from the [Copr](https://copr.fedorainfracloud.org/coprs/g/openscanhub/production/) repository. The process is documented on the [Fedora wiki](https://fedoraproject.org/wiki/OpenScanHub).

> * No mention of how to set it up locally via CLI

It is now documented on the [Fedora wiki](https://fedoraproject.org/wiki/OpenScanHub).

> * Took me a bit of time even to log in

I believe it was a temporary issue with the staging environment.

> * I found the page in the end to submit a scan via webui but since it's connected to stg.koji it wasn't too useful
> 

It is now documented on the [Fedora wiki](https://fedoraproject.org/wiki/OpenScanHub#How_to_use_it?). It should be more useful now.

> I suggest providing a simple-to-use guide how I can run a scan of a locally created SRPM.

I have listed it as an example on the [Fedora wiki](https://fedoraproject.org/wiki/OpenScanHub#Examples:) page.

I am closing this issue as either the items listed in the feedback are done, or they are being tracked separately through other issues.
